objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TEST</label>
</CustomObject>

objects/Customer__c.object
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/customerTriggerHandler.cls
public class customerTriggerHandler {
    //6.Casestudy when create customer record for account record will add to Account team
    public static void customerFunction(list<Customer__c> customerLst){
        list<string> teamRoleLst=new list<string>();
        set<Id> UserIds=new set<Id>();
        for(Customer__c cstmRec:customerLst){
            UserIds.add(cstmRec.Account_Manager__c);
        }
        Map<Id,User> userLst=new Map<Id,User>([SELECT Id,UserRole.Name
                                               FROM User
                                               WHERE Id in:UserIds]);
        list<AccountTeamMember> atmUpdate=new list<AccountTeamMember>();
        for(Customer__c rec:customerLst){
            teamRoleLst.add(rec.Account_Manager__c);
            AccountTeamMember obj=new AccountTeamMember(); 
            obj.AccountId=rec.Account__c;
            obj.UserId=rec.Account_Manager__c;
            obj.TeamMemberRole=userLst.get(rec.Account_Manager__c).UserRole.Name;
            atmUpdate.add(obj);
        }
        
        if(atmUpdate.size()>0){
            upsert atmUpdate;
        }
    }
}