objects/Attendee__c.object
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizer</label>
        <referenceTo>Event_Organi__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Event Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/Event_Organi__c.object
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organi Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Event Organizers</relationshipLabel>
        <relationshipName>Event_Organizers</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <label>Event - Speaker</label>
    <nameField>
        <label>Event - Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event - Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event - Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event - Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Landmark__c</fullName>
        <label>Landmark</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/CustomObjectController.cls
public with sharing class CustomObjectController {

    @AuraEnabled(cacheable=true)
    public static list<Event_Speaker__c> getEventSpeaker(string eventId){
        list<Event_Speaker__c> eventSpeakerLst=[SELECT 
                                                Id,Name,Speaker__r.Name,Speaker__r.Company__c,Event__c
                                                FROM 
                                                Event_Speaker__c
                                                WHERE
                                                Event__c=:eventId];
        return eventSpeakerLst;
    }

    @AuraEnabled(cacheable=true)
    public static list<Event_Attendee__c> getEventAttendees(string eventId){
        list<Event_Attendee__c> eventAttendeeLst=[SELECT
                                                Id,Event__c,Attendee__r.Name,Attendee__r.Address__c,Attendee__r.Company_Name__c
                                                FROM
                                                Event_Attendee__c
                                                WHERE
                                                Event__c =:eventId
                                                ];
        return eventAttendeeLst;
                                                
    }

    @AuraEnabled(cacheable=true)
    public static list<Event__c> getLocation(string eventId){
        list<Event__c> locationLst=[SELECT
                                    Id,Location__r.Name,Location__r.Street__c,Location__r.State__c,Location__r.City__c,
                                    Location__r.Country__c,Location__r.Landmark__c
                                    FROM
                                    Event__c
                                    WHERE
                                    Id=:eventId
                                    ];
                                    return locationLst;
    }

    @AuraEnabled(cacheable=true)
    public static list<Event_Attendee__c> getAttendeesForUpcoming(string attendeeId){
        list<Event_Attendee__c> eventAttendeeLst=[SELECT
                                                 Name,Event__c,Event__r.Name,Event__r.Name__c,Event__r.Live__c,
                                                 Event__r.Start_Date__c,Event__r.Event_Type__c,Event__r.Location__c,
                                                 Event__r.Location__r.Name,Event__r.Organizer__r.Name,
                                                 Attendee__c
                                                 FROM Event_Attendee__c
                                                 WHERE Attendee__c = :attendeeId
                                                 AND Event__r.Start_Date__c >= today
                                                 AND Event__r.Live__c = true
                                                ];
        return eventAttendeeLst;
                                                
    }
    @AuraEnabled(cacheable=true)
    public static list<Event_Attendee__c> getAttendeesForPastEvent(string attendeeId){
                                                list<Event_Attendee__c> eventAttendeeLst=[SELECT
                                                Name,Event__c,Event__r.Name,Event__r.Name__c,Event__r.Live__c,
                                                Event__r.Start_Date__c,Event__r.Event_Type__c,Event__r.Location__c,
                                                Event__r.Location__r.Name,Event__r.Organizer__r.Name,
                                                Attendee__c
                                                FROM Event_Attendee__c
                                                WHERE
                                                Attendee__c = :attendeeId AND Event__r.Start_Date__c < today
                                                ];
        return eventAttendeeLst;
                                                
    }
}