objects/Attendee__c.object
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Event Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/EventAttendeeTrigger_Test.cls
@isTest
public class EventAttendeeTrigger_Test {
    @testSetup
    public static void loadData(){
        Event__c eObj=new Event__c();
        eObj.Name__c='TestTrigger1';
        eObj.Live__c=true;
        eObj.Max_Seats__c=10;
        eObj.Start_Date__c=dateTime.newInstance(2022, 03, 01);
        eObj.End_Date__c=dateTime.now();
        insert eObj;
        Attendee__c aObj=new Attendee__c();
        aObj.Name='TestAttendee1';
        aObj.Phone__c='1010101010';
        aObj.Email__c='kvetrivel919@gmail.com';
        insert aObj;
    }
    testMethod
        public static void doTest(){
            integer returnValue;
            list<Event__c> eventLst=[SELECT Id FROM Event__c];
            list<Attendee__c> attendeeLst=[SELECT Id FROM Attendee__c];
            
            Event_Attendee__c obj=new Event_Attendee__c();
            obj.Attendee__c=attendeeLst[0].id;
            obj.Event__c=eventLst[0].id;
            obj.Name='TestAttendee1';
            insert obj;
            
            returnValue=EventAttendeeTriggerHandler.emailSent(new List<Event_Attendee__c>{obj});
            list<Event_Attendee__c> eventAttendeeLst=[SELECT Id FROM Event_Attendee__c];
            system.assertEquals(1, eventAttendeeLst.size(), 'Error in Message');
            system.assertEquals(2, returnValue, 'Error in Message');
        }
}