objects/Customer_Project__c.object
<CustomObject>
    <label>Customer Project</label>
    <nameField>
        <label>Customer Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Projects</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Active_Customer_Project__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Customer Project</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/customerProjectTriggerHandler.cls
/*
* @Name=Test Class
* @Author=vetrivel
* @Date=29-01-2023
* @Description= trigger case study day.
* *************************************
* Modification log:-
* -----------------------------------------------------
* version		Developer		Date		Description
* 0.1			vetrivel		29-01-2023	case study
* ----------------------------------------------------
*/
public class customerProjectTriggerHandler {
    //4.Casestudy when create the customer project record with status Active update opportunity checkbox istrue
    public static void createCustomerProject(list<Customer_Project__c> cpInput){
        string status;
        string aStatus='Active';
        string oppId;
        boolean checkbox=true;
        list<Opportunity> oppLst=new list<Opportunity>();
        for(Customer_Project__c cpIds:cpInput){
            status=cpIds.Status__c;
            oppId=cpIds.Opportunity__c;
            if(status==aStatus && oppId!=NULL){
                Opportunity oppObj=new Opportunity();
                oppObj.Id=oppId;
                oppObj.Active_Customer_Project__c=checkbox;
                oppLst.add(oppObj);
            }
        }
        if(oppLst.size()>0){
            upsert oppLst;
        }
    }
}