objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <label>Event - Speaker</label>
    <nameField>
        <label>Event - Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event - Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event - Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/EventSpeakerTriggerHandler.cls
public class EventSpeakerTriggerHandler {
    public static decimal preventEvent(list<Event_Speaker__c> newLst){
        list<string> eventIds=new list<string>();
        for(Event_Speaker__c  rec:newLst){
            eventIds.add(rec.Event__c);
        }
        list<Event_Speaker__c> eventSpeakerLst=[SELECT id,Event__c FROM Event_Speaker__c WHERE Event__c in:eventIds];
        system.debug(eventSpeakerLst);
        if(eventSpeakerLst.size()>0){
            for(Event_Speaker__c  rec:newLst){
                rec.Event__c.addError('Cant Select The Existing Event,Please Try Another Event');
            }
        }
        return eventSpeakerLst.size();
    }
}