objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <label>Event - Speaker</label>
    <nameField>
        <label>Event - Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event - Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event - Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event - Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
</CustomObject>

classes/EventSpeakerTrigger_Test.cls
@isTest
public class EventSpeakerTrigger_Test {
    @testSetup
    public static void LoadData(){
        list<Event__c> entLst=new list<Event__c>();
        for(integer i=1;i<3;i++){
            Event__c eObj=new Event__c();
            eObj.Name__c='TestTrigger'+i;
            eObj.Live__c=true;
            eObj.Start_Date__c=dateTime.newInstance(2022, 03, 01);
            eObj.End_Date__c=dateTime.now();
            entLst.add(eObj);
        }
        insert entLst;
        Speaker__c sObj=new Speaker__c();
        sObj.Name='TestSpeaker1';
        sObj.Phone__c='1010101010';
        insert sObj;
        list<Event__c> eventLst=[SELECT id FROM Event__c];
        list<Speaker__c> speakerLst=[SELECT id FROM Speaker__c];
        if(eventLst.size()>0 && speakerLst.size()>0){
            for(integer i=0;i<2;i++){
                Event_Speaker__c obj=new Event_Speaker__c();
                obj.Event__c=eventLst[i].id;
                obj.Speaker__c=speakerLst[0].id;
                obj.Name='TestEvent1';
                insert obj;
            }
        }        
    }
    
    testMethod
        public static void doTest(){
            decimal returnInsertValue;
            decimal returnUpdateValue;
            list<Event__c> eventLst=[SELECT id FROM Event__c];
            list<Speaker__c> speakerLst=[SELECT id FROM Speaker__c];
            Event_Speaker__c obj=new Event_Speaker__c();
            obj.Event__c=eventLst[0].id;
            obj.Speaker__c=speakerLst[0].id;
            obj.Name='TestEvent2';
            
            returnInsertValue=EventSpeakerTriggerHandler.preventEvent(new List<Event_Speaker__c>{obj});
            list<Event_Speaker__c> eventSpeakerLst=[SELECT id FROM Event_Speaker__c];
            Event_Speaker__c eObj=eventSpeakerLst[1];
            eObj.Event__c=eventLst[0].id;
            Database.update(eObj, false);
            returnUpdateValue=EventSpeakerTriggerHandler.preventEvent(new List<Event_Speaker__c>{eObj});
            
            system.assertEquals(1, returnInsertValue, 'Error not Shown ');
            system.assertEquals(eventSpeakerLst[1].Event__c, eventSpeakerLst[1].Event__c, 'Error not Shown ');
            system.assertEquals(2, eventSpeakerLst.size(), 'Error not Shown ');
        }
}