objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>post Poned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>People_Attending__c</fullName>
        <label>People Attending</label>
        <summaryForeignKey>Event_Attendee__c.Event__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

classes/EventController.cls
public with sharing class EventController {

    @AuraEnabled(Cacheable=true)
    public static List<List<SObject>> searchEventRecord(string Name){
        List<List<SObject>> eventLst= [FIND :Name IN ALL FIELDS RETURNING Event__c(Name__c)];
        return eventLst;
    }

    @AuraEnabled(Cacheable=true)
    public static list<Event__C> getEventRecord(){
        list<Event__c> eventLst=[SELECT  Name__c FROM Event__c];
        return eventLst;
    }

    @AuraEnabled(Cacheable=true)
    public static list<Event__C> getEventDetailRecord(string eventId){
        list<Event__c> eventLst=[SELECT  Name__c,Status__c,Start_Date__c,End_Date__c,Event_Type__c,
                                Max_Seats__c,People_Attending__c,Live__c FROM Event__c WHERE Id=:eventId];
        return eventLst;
    }

    @AuraEnabled(Cacheable=true)
    public static list<Event__C> getEventRecordForEventComp(){
        list<Event__c> eventLst=[SELECT  Name__c,Start_Date__c,End_Date__c,Event_Type__c,
                                Max_Seats__c,People_Attending__c,Live__c
                                 FROM Event__c WHERE Start_Date__c >=TODAY AND Live__c=true ];
        return eventLst;
    }

}