objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Market Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Number__c</fullName>
        <label>Market Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zone_Number__c</fullName>
        <label>Zone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market_Number__c</fullName>
        <label>Market Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <label>Zone</label>
    <nameField>
        <displayFormat>ZC-{0000}</displayFormat>
        <label>Zone Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone_Number__c</fullName>
        <label>Zone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/BatchStore.cls
public class BatchStore implements database.Batchable<sObject>,database.stateful{
    string errorEmailBody;
    string toAddress;
    string subject;
    string body;   
    list<string> errorLst=new list<string>();
    public database.QueryLocator start(database.BatchableContext context){
        string query='SELECT Id,Name,Market__c,Zone__c,Market_Number__c,Zone_Number__c FROM Store__c WHERE ';
        query+='Market_Number__c!=NULL OR Zone_Number__c!=NULL';
        return database.getQueryLocator(query);   
    }
    public void execute(database.BatchableContext context,list<sObject> store){
        errorLst=BatchStoreHandler.updateZoneMarketMapping(store);
        errorEmailBody=string.join(errorLst, '\n');
    }
    public void finish(database.BatchableContext context){
        AsyncApexJob jobLst=[
            SELECT
            Id,Status,TotalJobItems,JobItemsProcessed,NumberOfErrors
            FROM
            AsyncApexJob
            WHERE id=:context.getJobId()
        ];
        
        toAddress=userInfo.getUserEmail();
        subject= context.getJobId()+' - Batch Store Job status';
        body='Scheduled Batch Abc company Job status :: '+jobLst.Status+'\n';
        body+='Total Job Items Runs :: '+jobLst.TotalJobItems+'\n';
        body+='Total Job Items Processed :: '+jobLst.JobItemsProcessed+'\n';
        body+='Total Number Of Errors in Job :: '+jobLst.NumberOfErrors+'\n';
        if(errorEmailBody!=NULL){
            body+=errorEmailBody;
        }
        system.debug(toAddress);
        system.debug(subject);
        system.debug(body);
        EmailUtility.sendEmail(toAddress,subject,body);
    }
}