objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Market Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Number__c</fullName>
        <label>Market Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zone_Number__c</fullName>
        <label>Zone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market_Number__c</fullName>
        <label>Market Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <label>Zone</label>
    <nameField>
        <displayFormat>ZC-{0000}</displayFormat>
        <label>Zone Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone_Number__c</fullName>
        <label>Zone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/BatchZoneMarketHandler.cls
public class BatchZoneMarketHandler {
    public static string updateMarketZoneCode(list<Store__c> scope){
        system.debug(scope.size());
        list<Decimal> zoneNumberNotContainsLst=new list<Decimal>();
        list<Decimal> marketNumberNotContainsLst=new list<Decimal>();
        list<Decimal> zoneNumberLst=new list<Decimal>();
        list<Decimal> marketNumberLst=new list<Decimal>();
        list<String> errorLst=new list<string>();
        string errorMessages;
        for(Store__c storeRec:scope){
            zoneNumberLst.add(storeRec.Zone_Number__c);
            marketNumberLst.add(storeRec.Market_Number__c);
        }
        if(zoneNumberLst.size()>0){
            Zone__c[] zoneQueryLst=[
                SELECT
                Id,Zone_Number__c
                FROM
                Zone__c
                WHERE Zone_Number__c in:zoneNumberLst
            ];
            for(Decimal Rec:zoneNumberLst){
                for(Zone__c zRec:zoneQueryLst){
                    if(Rec!=zRec.Zone_Number__c){
                        zoneNumberNotContainsLst.add(Rec);
                        //system.debug(zoneNumberNotContainsLst);
                    }
                }
            }
            if(marketNumberLst.size()>0){
                Market__c[] marketQueryLst=[
                    SELECT
                    Id,Market_Number__c
                    FROM
                    Market__c
                    WHERE Market_Number__c in:marketNumberLst
                ];
                for(Decimal Rec:marketNumberLst){
                    for(Market__c zRec:marketQueryLst){
                        if(Rec!=zRec.Market_Number__c){
                            marketNumberNotContainsLst.add(Rec);
                            //system.debug(marketNumberNotContainsLst);
                        }
                    }
                }
                errorLst.add(ZoneCreationMappingService.zoneContainsNumberMapping(marketNumberLst,marketQueryLst,
                                                                                  zoneNumberLst,zoneQueryLst,scope));
                
                errorLst.add(ZoneCreationMappingService.zoneNotContainsNumberMapping(zoneNumberNotContainsLst,marketNumberNotContainsLst
                                                                                     ,marketQueryLst,zoneQueryLst,scope));
            }
        }
        if(errorLst.size()>0){
            errorMessages=string.join(errorLst, '\n');
        }
        return errorMessages;
    }
}