objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Market Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Name__c</fullName>
        <label>Market Name</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Number__c</fullName>
        <label>Market Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market_Manager__c</fullName>
        <label>Market Manager</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Description__c</fullName>
        <label>Market Description</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Number__c</fullName>
        <label>Market Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <label>Zone</label>
    <nameField>
        <displayFormat>ZC-{0000}</displayFormat>
        <label>Zone Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MarketCreationService.cls
public class MarketCreationService {
    public static void marketCreation(list<Decimal> withoutIdMarketNumberLst,list<Store__c> store){
        Map<Decimal,string> createdMarketMap=new Map<Decimal,string>();
        list<Market__c> marketLst=new list<Market__c>();
        if(withoutIdMarketNumberLst.size()>0){
            for(integer i=0;i<withoutIdMarketNumberLst.size();i++){
                Market__c mObj=new Market__c();
                mObj.Market_Name__c='Unknown Market'+i;
                mObj.Market_Manager__c='peter';	 
                mObj.Market_Number__c=withoutIdMarketNumberLst[i];
                mObj.Market_Description__c='There is no Market enter in the store Record';
                marketLst.add(mObj);
            }
            
            if(marketLst.size()>0){
                insert marketLst;
                for(Market__c mRec:marketLst){
                    createdMarketMap.put(mRec.Market_Number__c,mRec.Id);
                }
                system.debug('13:: market creation'+createdMarketMap);
            }
        }
        marketNumberMapping(createdMarketMap,store);
    }
    public static list<string>   marketNumberMapping(Map<Decimal,string> containsMarketNumberMap,list<Store__c> store){

        list<string> errorLst=new list<string>();
        for(Store__c sRec:store){
            if(containsMarketNumberMap.containsKey(sRec.Market_Number__c)&& sRec.Market__c==NULL &&sRec.Market_Number__c!=NULL&&sRec.Zone__c!=NULL){
                sRec.Market__c=containsMarketNumberMap.get(sRec.Market_Number__c);
                 system.debug('14:: market insert:'+sRec);
            }
        }
        database.SaveResult[] srResult=database.update(store, false);
        for(database.SaveResult rslt:srResult){
            for(database.Error er:rslt.getErrors()){
                errorLst.add(rslt.getId()+'Batch Store Job Market contains Error:: '+er.getMessage());
            }
        }
        return errorLst;
    }
}