objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Market Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Market_Number__c</fullName>
        <label>Market Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Number__c</fullName>
        <label>Market Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/MarketCheckService.cls
public class MarketCheckService {
    public static list<string> checkContainsMarketNumber(set<decimal> marketNumberLst,list<Store__c> store){
        list<string> errorLst=new list<string>();
        Map<Decimal,string> containsMarketNumberMap=new Map<Decimal,string>();
        list<Decimal> notContainsMarketNumberLst=new list<Decimal>();
        list<Market__c> marketQueryLst=[SELECT
                                        id,Market_Number__c
                                        FROM
                                        Market__c
                                        WHERE Market_Number__c in:marketNumberLst];
        for(Market__c mRec:marketQueryLst){
            containsMarketNumberMap.put(mRec.Market_Number__c,mRec.Id);
        }
        for(Decimal mRec:marketNumberLst){
            if(!containsMarketNumberMap.containsKey(mRec)){
                notContainsMarketNumberLst.add(mRec);
            }
        }
        system.debug('9:: market Class'+notContainsMarketNumberLst.Size());
        if(notContainsMarketNumberLst.size()>0){
            system.debug('11:: market Class notContainsMarketNumberLst');
            MarketCreationService.marketCreation(notContainsMarketNumberLst,store);
        }
        if(containsMarketNumberMap.size()>0){
            system.debug('12:: market Class containsMarketNumberMap');
            errorLst=MarketCreationService.marketNumberMapping(containsMarketNumberMap,store);
        }
        return errorLst;
    }
}