objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Market Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zone_Number__c</fullName>
        <label>Zone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <label>Zone</label>
    <nameField>
        <displayFormat>ZC-{0000}</displayFormat>
        <label>Zone Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone_Name__c</fullName>
        <label>Zone Name</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone_Leader__c</fullName>
        <label>Zone Leader</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone_Number__c</fullName>
        <label>Zone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zone_Description__c</fullName>
        <label>Zone Description</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

classes/ZoneCreationMappingService.cls
public class ZoneCreationMappingService {
    public static Zone__c zoneCreation(Decimal zoneNumber){
        Zone__c zObj=new Zone__c();
        zObj.Zone_Name__c='Unknown Zone';
        zObj.Zone_Leader__c='John';
        zObj.Zone_Number__c=zoneNumber;
        zObj.Zone_Description__c='There is no Zone enter in the store Record';
        return zObj;
    }
    public static string zoneContainsNumberMapping(list<Decimal> marketNumberLst,
                                                   list<Market__c> marketQueryLst,
                                                   list<decimal> zoneNumberLst,list<Zone__c> zoneQueryLst,list<Store__c> scope)
    {
        map<Decimal,string> zoneMapContainsId=new map<Decimal,string>();
        list<String> errorLst=new list<string>();
        string errorMessages;
        if(zoneQueryLst.size()>0){
            for(Zone__c rec:zoneQueryLst){
                if(zoneNumberLst.contains(rec.Zone_Number__c)){
                    zoneMapContainsId.put(rec.Zone_Number__c,rec.Id);
                }
            }
            for(Store__c storeRec:scope){
                if(storeRec.Zone__c==NULL && zoneMapContainsId.Containskey(storeRec.Zone_Number__c)){
                    storeRec.Zone__c=zoneMapContainsId.get(storeRec.Zone_Number__c);
                    system.debug('1.zoneContainsNumberMapping ::' +storeRec);
                }
            }
            if(zoneMapContainsId.values().size()>0){
                database.SaveResult[] srResult=database.update(scope,False);
                for(database.SaveResult rslt:srResult){
                    if(!rslt.isSuccess()){
                        for(Database.Error er:rslt.getErrors()){
                            errorLst.add(rslt.getId()+' - JobId ::Batch zoneMarket Job contains Error in ZoneId::'+er.getMessage());
                        }
                    }
                } 
            }
        }
        
        errorLst.add(MarketCreationMappingServices.MarketContainsNumberMapping(marketNumberLst,marketQueryLst,scope));
        errorMessages=string.join(errorLst,',');
        return errorMessages;
    }
    public static string zoneNotContainsNumberMapping(list<Decimal> zoneNumberNotContainsLst,list<Decimal> marketNumberNotContainsLst,
                                                      list<Market__c> marketQueryLst,list<Zone__c> zoneQueryLst,list<Store__c> scope)
    {
        map<Decimal,string> zoneMap=new map<Decimal,string>();
        list<Zone__c> zoneInsertLst=new list<Zone__c>();
        list<String> errorLst=new list<string>();
        string errorMessages;
        if(zoneNumberNotContainsLst.size()>0){
            for(Store__c storeRec:scope){
                if(storeRec.Zone__c==NULL){
                    zoneInsertLst.add(ZoneCreationMappingService.zoneCreation(storeRec.Zone_Number__c));
                }
            }
            if(zoneInsertLst.size()>0){
                insert zoneInsertLst;
                for(Zone__c rec:zoneInsertLst){
                    zoneMap.put(rec.Zone_Number__c,rec.Id);
                }
                
                for(Store__c storeRec:scope){
                    if(storeRec.Zone__c==NULL){
                        storeRec.Zone__c=zoneMap.get(storeRec.Zone_Number__c);
                        system.debug('2.zoneNotContainsNumberMapping ::' +storeRec);
                    }
                }
                database.SaveResult[] srResult=database.update(scope,False);
                for(database.SaveResult rslt:srResult){
                    if(!rslt.isSuccess()){
                        for(Database.Error er:rslt.getErrors()){
                            errorLst.add(rslt.getId()+' - JobId ::Batch zoneMarket Job contains Error in ZoneId::'+er.getMessage());
                        }
                    }
                }
            }
        }
        errorLst.add(MarketCreationMappingServices.MarketNotContainsNumberMapping(marketNumberNotContainsLst,marketQueryLst,scope));
        errorMessages=string.join(errorLst,',');
        return errorMessages;
    }
}