objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zone_Number__c</fullName>
        <label>Zone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <label>Zone</label>
    <nameField>
        <displayFormat>ZC-{0000}</displayFormat>
        <label>Zone Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Zone_Name__c</fullName>
        <label>Zone Name</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone_Leader__c</fullName>
        <label>Zone Leader</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone_Number__c</fullName>
        <label>Zone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zone_Description__c</fullName>
        <label>Zone Description</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

classes/zoneCreationService.cls
public class zoneCreationService {
    public static void zoneCreation(set<decimal> marketNumberLst,list<Decimal> withoutIdZoneNumberLst,list<Store__c> store){
        Map<Decimal,string> createdZoneMap=new Map<Decimal,string>();
        list<Zone__c> zoneLst=new list<Zone__c>();
        if(withoutIdZoneNumberLst.size()>0){
            for(integer i=0;i<withoutIdZoneNumberLst.size();i++){
                Zone__c zObj=new Zone__c();
                zObj.Zone_Name__c='Unknown Zone'+i;
                zObj.Zone_Leader__c='John';
                zObj.Zone_Number__c=withoutIdZoneNumberLst[i];
                zObj.Zone_Description__c='There is no Zone enter in the store Record';
                zoneLst.add(zObj);
            }
            system.debug('6:: ZoneCreation size::'+zoneLst.size());
            if(zoneLst.size()>0){
                insert zoneLst;
                for(Zone__c zRec:zoneLst){
                    system.debug('6.1:: ZoneCreation'+zRec.Id);
                    createdZoneMap.put(zRec.Zone_Number__c,zRec.Id);
                }
            }
        }
        if(createdZoneMap.keyset().size()>0){
            system.debug('6.2:: ZoneCreation'+createdZoneMap.keyset().size());
            zoneNumberMapping (marketNumberLst,createdZoneMap,store);
        }
    }
    public static list<string> zoneNumberMapping(set<decimal> marketNumberLst,Map<Decimal,string> zoneMappingMap,list<Store__c> store){
        list<string> errorLst=new list<string>();
        for(Store__c sRec:store){
            if(zoneMappingMap.containskey(sRec.Zone_Number__c)){
                system.debug('7:: Zoneinsert'+zoneMappingMap.get(sRec.Zone_Number__c));
                sRec.Zone__c=zoneMappingMap.get(sRec.Zone_Number__c);
            }
        }
        database.SaveResult[] srResult=database.update(store, false);
        for(database.SaveResult rslt:srResult){
            for(database.Error er:rslt.getErrors()){
                errorLst.add(rslt.getId()+'Batch Store Job Zone contains Error:: '+er.getMessage());
            }
        }
        if(marketNumberLst.size()>0){
            system.debug('8:: market Class');
            errorLst=MarketCheckService.checkContainsMarketNumber(marketNumberLst,store);
        }
        return errorLst;
    }
}